# Site settings
name: Braden Shaak
description: "Software Developer"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  bShaak
twitter_username: beedSafeHaveFun
#linked_in_username: your_linked_in_username_goes_here
#instagram_username:  snor_lax
stack_of_username: 3550406
#blog_url: "/blog"
email: your-email@example.domain


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/jetty.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
